### ISSUE TITLE
[PE-D][Tester C] Product could allow editing of appointments

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-1/tp#104]
Currently, appointments in the app can only be added (via the `sched` command) or deleted (via the `unsched` command). This level of functionality is good, but it would be even better to allow clients to edit their appointments as well, as practically, many aspects of an appointments could change, such as the address and start time. This would be more efficient and user-friendly than deleting and re-adding the whole appointment.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kjw142857/ped#8

**Comment by camille-readbean** [comment]
Similar to #119
