### ISSUE TITLE
[PE-D][Tester E] Disorganized user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-1/tp#114]
The user guide appears messy, as it jumps from one test case to another without a clear flow. 

For example, the instruction directed me to execute the exit feature but then immediately moved on to scheduling an appointment for clients. It would be better if the exit test case appears at the very end. 

Exit command appears before some other commands:
![image.png](https://raw.githubusercontent.com/yap-zong-xin/ped/main/files/7a52c5ff-896e-40c5-a757-e1f835b2fbcf.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yap-zong-xin/ped#8

**Comment by vannykin** [comment]
Same as Issue #111
