### ISSUE TITLE
[PE-D][Tester E] Allowing overlapping appointments

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-1/tp#118]
The system currently permits users to schedule multiple overlapping appointments, even though this action should not be allowed according to the standard appointment protocol. This oversight could lead to scheduling conflicts, confusion, and potential disruptions in the appointment management process.

The following screenshots shows two appointments with overlapping time slots in the same day: 

![Screenshot 2024-04-05 185140.png](https://raw.githubusercontent.com/yap-zong-xin/ped/main/files/c8c44bc5-6749-4acd-9a02-eb358af0814f.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: yap-zong-xin/ped#11

**Comment by vannykin** [comment]
Same as Issue #86
