### ISSUE TITLE
[v1.2] Improve the Developer Guide: use cases

### ISSUE THREAD

**Issue by GiselleTan** [AY2324S2-CS2103T-T17-1/tp#14]
See:
https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#4-update-the-dg-user-stories-glossary-nfrs-use-cases

Improve:
- [ ] Use cases

**Comment by camille-readbean** [comment]
Closed, moving https://github.com/AY2324S2-CS2103T-T17-1/tp/pull/12 to 1.2b backlog i guess so we can close v1.2
