### ISSUE TITLE
[PE-D][Tester C] Product does not allow adding or editing of hyphenated names

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T17-1/tp#92]
If an attempt is made to add/edit a person with a hyphenated name, SWEE returns the "name should only contain alphanumeric characters and spaces message". This may cause problems for people who need to remember their contacts' exact names.

![image.png](https://raw.githubusercontent.com/kjw142857/ped/main/files/3114cda2-c6f4-4a9f-90c2-af2300d33e81.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kjw142857/ped#4

**Comment by camille-readbean** [comment]
Planned fix: specify format for name

**Comment by TheodoreKooo** [comment]
Doesn't the error message already specify that only alphanumeric and spaces are allowed? So the user is already informed that hyphens are not allowed.
