### ISSUE TITLE
[PE-D][Tester A] Missing address in the command example for 'scheduling an appointment for clients'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-1/tp#96]
**Describe the bug**
Missing address in the example

**To Reproduce**
1. Navigate to the 'Scheduling an appointment for clients' in the UG (page 16)

**Expected behavior**
 The format should be complete with the address

**Screenshots**
![Screenshot 2024-04-05 at 4.39.37 PM.png](https://raw.githubusercontent.com/Jajared/ped/main/files/b58d98d2-7215-4cce-8f15-730c1db7f42a.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Jajared/ped#4

**Comment by vannykin** [comment]
Same as Issue #83
