### ISSUE TITLE
[PE-D][Tester D] Can add phone number to client that has length of 1000 digits

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-1/tp#99]
**Description:**  Users are able to add phone numbers that have length 1000 digits, and phone number is unable to be displayed entirely, instead cutting off at maximum screen size

**Steps to reproduce:** 
1. Use `edit` and enter a phone number that has a length of 1000 digits

**Expected:** Should not be able to add phone numbers that exceed the length of standard phone number formats (8 digits or country code + 8 digits)

**Actual:**
![Screenshot 2024-04-05 at 4.45.52 PM.png](https://raw.githubusercontent.com/thewongdylan/ped/main/files/faad4e64-7a0d-4c04-81f3-f68d1f7a16b6.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: thewongdylan/ped#7

**Comment by camille-readbean** [comment]
This is not considered normal behavior. Adding support for this will be considered an enhancement. Will not fix

See: https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html
